Repository uqbar-project/wollok, pull requests merged in 2018-03, with the labels that each got.

#1328 Avoid to run type system while typing
  org.uqbar.project.wollok.typeSystem.xsemantics.ui/src/org/uqbar/project/wollok/typeSystem/xsemantics/ui/labeling/XSemanticsWollokTypeSystemLabelExtension.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/AbstractContainerWollokType.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/WollokTypeSystemActivator.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/ConstraintBasedTypeSystem.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/strategies/AbstractInferenceStrategy.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/strategies/MaxTypesFromMessages.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/MaximalConcreteTypes.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/SimpleTypeInfo.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/TypeInfo.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/TypeVariable.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/TypeVariablesRegistry.xtend
  org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/labeling/WollokDslLabelProvider.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/validation/NotConfigurable.java
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/validation/WollokDslValidator.xtend
Labels: in progress

#1330 Support message sending to closures
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/ClosureInferenceTestCase.xtend
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/closures.wpgm.xt
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/methods.wpgm.xt
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/TypeDeclarations.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/WollokCoreTypeDeclarations.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/strategies/OpenMethod.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/strategies/UnifyVariables.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/ClassParameterTypeVariable.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/ClosureTypeInfo.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/MessageSend.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/TypeVariable.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/TypeVariablesRegistry.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/WollokClassFinder.xtend
Labels: in progress

#1339 Type system additional checks
  org.uqbar.project.wollok.lib/src/wollok/lang.wlk
  org.uqbar.project.wollok.lib/src/wollok/lib.wlk
  org.uqbar.project.wollok.lib/src/wollok/mirror.wlk
  org.uqbar.project.wollok.tests/src/log4j-normal.properties
  org.uqbar.project.wollok.tests/src/log4j-travis.properties
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/debugger/DebugWithoutThreadingTestCase.xtend
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/ListTestCase.xtend
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/WollokComparisonFailure.xtend
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/namedobjects/NamedObjectInheritanceTest.xtend
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/asserts.wlk.xt
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/booleans.wlk.xt
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/console.wpgm.xt
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/dates.wlk.xt
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/exceptions.wlk.xt
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/methods.wpgm.xt
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/numbers.wlk.xt
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/operators.wlk.xt
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/pair.wlk.xt
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/strings.wlk.xt
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/SuperInvocation.wlk.xt
  org.uqbar.project.wollok.typeSystem.xsemantics/src/org/uqbar/project/wollok/semantics/WollokDsl.xsemantics
  org.uqbar.project.wollok.typeSystem.xsemantics/xsemantics-gen/org/uqbar/project/wollok/semantics/WollokDslTypeSystem.java
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/ClassBasedWollokType.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/TypeDeclarations.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/WollokCoreTypeDeclarations.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/ConstraintGenerator.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/WollokModelPrintForDebug.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/strategies/GuessMinTypeFromMaxType.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/VoidTypeInfo.xtend
  org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/console/actions/WollokReplConsoleActionsParticipant.xtend
  org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/console/highlight/WollokReplConsolePageParticipant.xtend
  org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/i18n/messages.properties
  org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/i18n/messages_es.properties
  org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/launch/WollokLaunchConstants.xtend
  org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/launch/handlers/LaunchReplWithoutFileHandler.xtend
  org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/launch/shortcut/WollokLaunchDelegate.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WollokModelExtensions.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/sdk/WollokDSK.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/validation/WollokDslValidator.xtend
Labels: component: type system, in progress

#1343 fix 1341 - allow to annotate constructors types for core classes.
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/AbstractWollokTypeSystemTestCase.xtend
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/TypeSystemXpectTestCase.xtend
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/constructors.wlk.xt
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/ClassBasedWollokType.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/ConcreteType.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/TypeSystemUtils.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/TypeAnnotation.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/TypeDeclarationTarget.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/TypeDeclarations.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/WollokCoreTypeDeclarations.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/typeRegistry/AnnotatedTypeRegistry.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WollokModelExtensions.xtend
Labels: in progress

#1338 Game general background
  org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/Image.xtend
  org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/ImageSize.xtend
  org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/gameboard/Background.xtend
  org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/gameboard/Cell.xtend
  org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/gameboard/Gameboard.xtend
  org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/gameboard/Window.xtend
  org.uqbar.project.wollok.lib/src/org/uqbar/project/wollok/lib/WImage.xtend
  org.uqbar.project.wollok.lib/src/wollok/lib.wlk
  org.uqbar.project.wollok.lib/src/wollok/lib/GameObject.xtend
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/game/BackgroundTest.xtend
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/game/GameboardTest.xtend
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/game/ImageTest.xtend
Labels: in progress

#1347 Fix 1346 constructor call constraints
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/constructors.wlk.xt
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/WollokCoreTypeDeclarations.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/ConstraintBasedTypeSystem.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/ConstraintGenerator.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/ConstructorConstraintsGenerator.xtend
  org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/editor/annotations/WOverrideIndicatorModelListener.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/WollokInterpreterEvaluator.xtend
Labels: in progress

#1345 Fix #1334
  org.uqbar.project.wollok.lib/src/wollok/lang.wlk
  org.uqbar.project.wollok.lib/src/wollok/lang/Closure.xtend
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/ClosureTestCase.xtend
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/NumberTestCase.xtend
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/RangeTestCase.xtend
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/sdk/GameTest.xtend
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/sdk/PositionTest.xtend
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/jugador.wlk.xt
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/types/VariableSubtypingRules.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/Messages.java
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/WollokInterpreterEvaluator.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages.properties
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages_es.properties
Labels: component: interpreter, in progress
