Repository uqbar-project/wollok, pull requests merged in 2018-07, with the labels that each got.

#1426 #1424 type for closures using class type parameters
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/closures-advanced.wlk.xt
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/list.wlk.xt
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/TypeAnnotation.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/TypeDeclarations.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/WollokCoreTypeDeclarations.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/strategies/PropagateMinimalTypes.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/typeRegistry/AnnotatedTypeRegistry.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/AnalysisResultReporter.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/ClassParameterTypeVariable.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/GenericTypeInfo.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/MinTypeAnalysisResultReporter.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/TypeInfo.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/TypeVariable.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/VoidTypeInfo.xtend
Labels: in progress

#1350 Type System as a Builder
  org.uqbar.project.wollok.game/pom.xml
  org.uqbar.project.wollok.launch/pom.xml
  org.uqbar.project.wollok.launch/src/log4j.properties
  org.uqbar.project.wollok.lib/pom.xml
  org.uqbar.project.wollok.product.ui/META-INF/MANIFEST.MF
  org.uqbar.project.wollok.product.ui/plugin.xml
  org.uqbar.project.wollok.product.ui/pom.xml
  org.uqbar.project.wollok.product.ui/src/org/uqbar/project/wollok/product/ui/Messages.java
  org.uqbar.project.wollok.product.ui/src/org/uqbar/project/wollok/product/ui/messages.properties
  org.uqbar.project.wollok.product.ui/src/org/uqbar/project/wollok/product/ui/messages_es.properties
  org.uqbar.project.wollok.product.ui/src/org/uqbar/project/wollok/product/ui/startup/AutoBuildAtStartup.xtend
  org.uqbar.project.wollok.product.ui/src/org/uqbar/project/wollok/product/ui/startup/RemoveWizardsStartup.xtend
  org.uqbar.project.wollok.releng/pom.xml
  org.uqbar.project.wollok.tests/pom.xml
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/AbstractWollokTypeSystemTestCase.xtend
  org.uqbar.project.wollok.typeSystem.ui/META-INF/MANIFEST.MF
  org.uqbar.project.wollok.typeSystem.ui/plugin.xml
  org.uqbar.project.wollok.typeSystem.ui/pom.xml
  org.uqbar.project.wollok.typeSystem.ui/src/org/uqbar/project/wollok/typeSystem/ui/labeling/WollokTypeSystemLabelExtensionImpl.xtend
  org.uqbar.project.wollok.typeSystem.ui/src/org/uqbar/project/wollok/typeSystem/ui/preferences/WollokTypeSystemUIPreferences.xtend
  org.uqbar.project.wollok.typeSystem.ui/src/org/uqbar/project/wollok/typesystem/ui/builder/WollokTypeSystemBuilderParticipant.xtend
  org.uqbar.project.wollok.typeSystem/pom.xml
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/TypeProvider.java
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/TypeSystem.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/WollokTypeSystemActivator.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/ConstraintBasedTypeSystem.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/ConstraintGenerator.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/typeRegistry/AnnotatedTypeRegistry.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/MessageSend.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/TypeVariable.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/TypeVariablesRegistry.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/preferences/DefaultWollokTypeSystemPreferences.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/preferences/WollokTypeSystemPreference.xtend
  org.uqbar.project.wollok.ui.diagrams/pom.xml
  org.uqbar.project.wollok.ui.launch/pom.xml
  org.uqbar.project.wollok.ui/pom.xml
  org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/WollokActivator.xtend
  org.uqbar.project.wollok/pom.xml
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/WollokConstants.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/errorHandling/HumanReadableUtils.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/libraries/AbstractWollokLib.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/libraries/BasicWollokLibraryLoader.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/libraries/StandardWollokLib.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/libraries/WollokLibExtensions.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WollokModelExtensions.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/scoping/WollokResourceCache.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/scoping/cache/MapBasedWollokGlobalScopeCache.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/utils/WEclipseUtils.xtend
  org.uqbar.project.xinterpreter/pom.xml
Labels: toCheck

#1429 fixing performance
  org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/VisualComponent.xtend
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/CollectionTestCase.xtend
Labels: in progress

#1430 Enhanced multifile behavior for TS builder
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/AbstractWollokTypeSystemTestCase.xtend
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/WollokTypeSystemTestInjector.xtend
  org.uqbar.project.wollok.typeSystem.ui/src/org/uqbar/project/wollok/typesystem/ui/builder/WollokTypeSystemBuilderParticipant.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/TypeSystem.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/ConstraintBasedTypeSystem.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/TypeVariablesRegistry.xtend
  org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/WollokActivator.xtend
  org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/validator/WollokResourceUIValidatorExtension.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/utils/WEclipseUtils.xtend
Labels: component: type system, in progress
