Repository uqbar-project/wollok, pull requests merged in 2018-04, with the labels that each got.

#1357 Fixing #1298 with tests
  org.uqbar.project.wollok.lib/src/wollok/lang/VoidObject.xtend
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/ClosureTestCase.xtend
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/NullTestCase.xtend
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/StringTestCase.xtend
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/VoidTestCase.xtend
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/VoidMethodsUsage.wlk.xt
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/Messages.java
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/WollokInterpreterEvaluator.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/core/WollokObject.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/operation/WollokDeclarativeNativeBasicOperations.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages.properties
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages_es.properties
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WMethodContainerExtensions.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/validation/WollokDslValidator.xtend
Labels: component: interpreter, in progress

#1355 Issue fixing & some TS tests
  README.md
  org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/WollokChecker.xtend
  org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/WollokLauncher.xtend
  org.uqbar.project.wollok.lib/src/wollok/lang.wlk
  org.uqbar.project.wollok.lib/src/wollok/lang/WNumber.xtend
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/dates.wlk.xt
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/pair.wlk.xt
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/DescribeTest.wtest.xt
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/TestWithNoAsserts.wtest.xt
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/TypeDeclarations.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/WollokCoreTypeDeclarations.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/ConstraintBasedTypeSystem.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/ConstraintGenerator.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/ConstructorConstraintsGenerator.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/ClassParameterTypeVariable.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/ClosureTypeInfo.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/GenericTypeInfo.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/TypeVariablesRegistry.xtend
  org.uqbar.project.wollok.ui.diagrams/src/org/uqbar/project/wollok/ui/diagrams/classes/StaticDiagramConfiguration.xtend
  org.uqbar.project.wollok.ui.diagrams/src/org/uqbar/project/wollok/ui/diagrams/classes/StaticDiagramView.xtend
  org.uqbar.project.wollok.ui.diagrams/src/org/uqbar/project/wollok/ui/diagrams/classes/actionbar/AddOutsiderClassView.xtend
  org.uqbar.project.wollok.ui.diagrams/src/org/uqbar/project/wollok/ui/diagrams/classes/actionbar/StaticDiagramToolbarActions.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/Messages.java
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/WollokInterpreterEvaluator.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/nativeobj/NumberCoercingStrategy.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/nativeobj/WollokJavaConversions.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/nativeobj/WollokNumbersPreferences.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages.properties
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages_es.properties
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WMethodContainerExtensions.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WollokModelExtensions.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/sdk/WollokDSK.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/utils/WEclipseUtils.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/validation/WollokDslValidator.xtend
Labels: in progress

#1369 fix: remove unused messages
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages_es.properties
Labels: in progress

#1365 Fix 1361 game aborts when removing objects on collision
  org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/listeners/CollisionListener.xtend
Labels: in progress

#1351 Ts adds mdnu
  org.uqbar.project.wollok.lib/src/wollok/lang/WObject.xtend
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/MethodTypeInferenceTestCase.xtend
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/console.wpgm.xt
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/methods.wpgm.xt
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/TypeSystemException.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/WollokTypeExtension.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/strategies/OpenMethod.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/strategies/SealVariables.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/types/OffenderSelector.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/GenericTypeInfo.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/MaximalConcreteTypes.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/MessageSend.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/TypeInfo.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/exceptions/MessageNotUnderstoodException.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/exceptions/RejectedMinTypeException.xtend
  org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/contentassist/WollokDslProposalProvider.xtend
  org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/hover/WollokEObjectHoverProvider.xtend
  org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/quickfix/WollokDslQuickfixProvider.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/WollokModelUtils.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/errorHandling/HumanReadableUtils.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/WollokInterpreterEvaluator.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/core/WollokObject.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/linking/WollokLinkingDiagnosticMessageProvider.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WollokModelExtensions.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/validation/WollokDslValidator.xtend
Labels: in progress

#1371 Fix #1359
  org.uqbar.project.wollok.launch/Generate WollokDoc.launch
  org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/WollokASTAnalyzer.xtend
  org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/WollokChecker.xtend
  org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/WollokLauncher.xtend
  org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/WollokLauncherInterpreterEvaluator.xtend
  org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/tests/WollokExceptionUtils.xtend
  org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/tests/WollokResultTestDTO.xtend
  org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/wollokDoc/WollokDocParser.xtend
  org.uqbar.project.wollok.lib/src/wollok/lib.wlk
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/WollokComparisonFailure.xtend
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/natives/ExceptionPropagationInNativeTestCase.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/WollokInterpreter.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/WollokInterpreterEvaluator.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/WollokSourcecodeLocator.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/core/WollokObject.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/threads/WThread.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/FlowControlExtensions.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/ui/utils/XTendUtilExtensions.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/validation/WollokDslValidator.xtend
  org.uqbar.project.xinterpreter/src/org/uqbar/project/xtext/utils/XTextExtensions.xtend
Labels: component: interpreter, component: wtests, in progress

#1373 1363 disallow effectless expressions in sequences
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/clazz/ConstructorTest.xtend
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/if.wpgm.xt
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/void.wpgm.xt
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/CheckOnNameStyles.wlk.xt
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/ConstructorCalls.wlk.xt
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/EffectlessExpressionsInSequence.wlk.xt
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/MultiOpsOperations.wlk.xt
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/dontUseLocalVarOnlyToReturn.wlk.xt
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/Messages.java
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages.properties
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages_es.properties
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WEvaluationExtension.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WollokModelExtensions.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/utils/XtendExtensions.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/validation/WollokDslValidator.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/visitors/AbstractVisitor.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/visitors/EffectFinderVisitor.xtend
Labels: in progress

#1387 partial-fix-1318-add-immutable-methods-to-position
  org.uqbar.project.wollok.lib/src/wollok/lib.wlk
Labels: in progress

#1386 fix: 1382 - avoid using File.separator to build URIs
  org.uqbar.project.wollok.game/.gitignore~
  org.uqbar.project.wollok.ui.diagrams/src/org/uqbar/project/wollok/ui/diagrams/classes/StaticDiagramConfiguration.xtend
  org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/wizard/abstractWizards/AbstractNewWollokFileWizardPage.java
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages_es.properties
Labels: in progress

#1389 Release 1.6.6
  org.uqbar.project.wollok.game/.gitignore~
  org.uqbar.project.wollok.game/META-INF/MANIFEST.MF
  org.uqbar.project.wollok.game/pom.xml
  org.uqbar.project.wollok.launch/META-INF/MANIFEST.MF
  org.uqbar.project.wollok.launch/pom.xml
  org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/Wollok.xtend
  org.uqbar.project.wollok.lib/META-INF/MANIFEST.MF
  org.uqbar.project.wollok.lib/pom.xml
  org.uqbar.project.wollok.lib/src/wollok/lib.wlk
  org.uqbar.project.wollok.product.ui.feature/feature.xml
  org.uqbar.project.wollok.product.ui.feature/pom.xml
  org.uqbar.project.wollok.product.ui/META-INF/MANIFEST.MF
  org.uqbar.project.wollok.product.ui/pom.xml
  org.uqbar.project.wollok.product/META-INF/MANIFEST.MF
  org.uqbar.project.wollok.product/plugin.xml
  org.uqbar.project.wollok.product/pom.xml
  org.uqbar.project.wollok.releng/pom.xml
  org.uqbar.project.wollok.sdk/feature.xml
  org.uqbar.project.wollok.sdk/pom.xml
  org.uqbar.project.wollok.targetplatform/pom.xml
  org.uqbar.project.wollok.tests/META-INF/MANIFEST.MF
  org.uqbar.project.wollok.tests/pom.xml
  org.uqbar.project.wollok.typeSystem.xsemantics.ui/META-INF/MANIFEST.MF
  org.uqbar.project.wollok.typeSystem.xsemantics.ui/pom.xml
  org.uqbar.project.wollok.typeSystem.xsemantics/META-INF/MANIFEST.MF
  org.uqbar.project.wollok.typeSystem.xsemantics/pom.xml
  org.uqbar.project.wollok.typeSystem/META-INF/MANIFEST.MF
  org.uqbar.project.wollok.typeSystem/pom.xml
  org.uqbar.project.wollok.ui.diagrams/META-INF/MANIFEST.MF
  org.uqbar.project.wollok.ui.diagrams/pom.xml
  org.uqbar.project.wollok.ui.diagrams/src/org/uqbar/project/wollok/ui/diagrams/classes/StaticDiagramConfiguration.xtend
  org.uqbar.project.wollok.ui.launch/META-INF/MANIFEST.MF
  org.uqbar.project.wollok.ui.launch/pom.xml
  org.uqbar.project.wollok.ui/META-INF/MANIFEST.MF
  org.uqbar.project.wollok.ui/pom.xml
  org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/wizard/abstractWizards/AbstractNewWollokFileWizardPage.java
  org.uqbar.project.wollok.updatesite/category.xml
  org.uqbar.project.wollok.updatesite/pom.xml
  org.uqbar.project.wollok.updatesite/wollok-product.product
  org.uqbar.project.wollok/META-INF/MANIFEST.MF
  org.uqbar.project.wollok/pom.xml
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages_es.properties
  org.uqbar.project.xinterpreter/META-INF/MANIFEST.MF
  org.uqbar.project.xinterpreter/pom.xml
Labels: in progress

#1397 Fix #1342 consructor type expectations
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/Instantation.wpgm.xt
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/instantiation.wpgm.xt
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/ConstraintGenerator.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/WollokModelPrintForDebug.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/strategies/AbstractInferenceStrategy.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/strategies/GuessMinTypeFromMaxType.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/TypeVariable.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/TypeVariablesRegistry.xtend
  org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/quickfix/WollokDslQuickfixProvider.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WMethodContainerExtensions.xtend
Labels: in progress
