Repository uqbar-project/wollok, pull requests merged in 2018-08, with the labels that each got.

#1437 Fix #1436 ts builder
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/AbstractWollokTypeSystemTestCase.xtend
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/ObjetoMensajeZapatero2.wlk.xt
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/if.wpgm.xt
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/methods.wpgm.xt
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/testFailures.wlk.xt
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/testGenericFailures.wlk.xt
  org.uqbar.project.wollok.typeSystem.ui/src/org/uqbar/project/wollok/typeSystem/ui/builder/WollokTypeSystemBuilderParticipant.xtend
  org.uqbar.project.wollok.typeSystem.ui/src/org/uqbar/project/wollok/typeSystem/ui/preferences/TypeSystemConfigurationBlock.xtend
  org.uqbar.project.wollok.typeSystem.ui/src/org/uqbar/project/wollok/typeSystem/ui/preferences/TypeSystemPreferencePage.xtend
  org.uqbar.project.wollok.typeSystem.ui/src/org/uqbar/project/wollok/typeSystem/ui/preferences/WollokTypeSystemUIPreferences.xtend
  org.uqbar.project.wollok.typeSystem.ui/xtend-gen/.gitignore
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/BasicType.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/ClassInstanceType.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/Constants.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/Messages.java
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/StructuralType.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/TypeSystemException.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/TypeSystemWollokValidatorExtension.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/WollokType.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/WollokTypeSystemActivator.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/TypeAnnotation.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/ConstraintBasedTypeSystem.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/ConstraintGenerator.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/strategies/GuessMinTypeFromMaxType.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/strategies/MaxTypesFromMessages.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/strategies/PropagateMaximalTypes.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/strategies/UnifyVariables.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/typeRegistry/MethodTypeProvider.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/types/OffenderSelector.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/types/SubtypingRules.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/ClassParameterTypeVariable.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/GenericTypeInfo.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/ITypeVariable.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/MessageSend.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/TypeInfo.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/TypeVariable.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/TypeVariableOwner.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/TypeVariablesRegistry.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/VoidTypeInfo.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/exceptions/RejectedMinTypeException.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/messages.properties
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/messages_es.properties
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/preferences/DefaultWollokTypeSystemPreferences.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/preferences/WollokTypeSystemPreference.xtend
  org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/WollokActivator.xtend
  org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/messages_es.properties
  org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/validator/WollokResourceUIValidatorExtension.xtend
  org.uqbar.project.wollok/META-INF/MANIFEST.MF
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/preferences/WollokCachedTypeSystemPreferences.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/utils/WEclipseUtils.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/validation/AbstractConfigurableDslValidator.xtend
Labels: in progress

#1445 Fix #1443 - Outline page refresh without ClassCast
  org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/WollokActivator.xtend
Labels: component: outline, in progress

#1447 Fix #1324 repl console mac
  org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/WollokLauncher.xtend
  org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/repl/WollokRepl.xtend
  org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/console/highlight/WollokAnsiColorLineStyleListener.xtend
  org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/console/highlight/WollokConsoleColorPalette.xtend
  org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/console/highlight/WollokReplConsolePageParticipant.xtend
Labels: in progress

#1449 Fixing #1398 and added a test
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/NumberTestCase.xtend
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/numbers/ArithmeticTest.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/nativeobj/NumberPrintingStrategy.xtend
Labels: in progress

#1450 Wollok game enhancements
  org.uqbar.project.wollok.game/META-INF/MANIFEST.MF
  org.uqbar.project.wollok.game/assets/speech2.png
  org.uqbar.project.wollok.game/assets/speech3.png
  org.uqbar.project.wollok.game/assets/speech4.png
  org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/BalloonMessage.xtend
  org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/Image.xtend
  org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/ImageSize.xtend
  org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/Messages.java
  org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/Position.xtend
  org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/VisualComponent.xtend
  org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/gameboard/Background.xtend
  org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/gameboard/Gameboard.xtend
  org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/gameboard/GameboardInputProcessor.xtend
  org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/gameboard/GameboardRendering.xtend
  org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/gameboard/Window.xtend
  org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/helpers/Keyboard.xtend
  org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/listeners/ArrowListener.xtend
  org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/listeners/KeyboardListener.xtend
  org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/listeners/TimeListener.xtend
  org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/messages.properties
  org.uqbar.project.wollok.game/src/org/uqbar/project/wollok/game/messages_es.properties
  org.uqbar.project.wollok.lib/src/wollok/lib.wlk
  org.uqbar.project.wollok.lib/src/wollok/lib/GameObject.xtend
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/game/ArrowListenerTest.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/Messages.java
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages.properties
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/messages_es.properties
Labels: component: wollokgame, in progress

#1446 Fixes for #1390 #1419 #1418
  org.uqbar.project.wollok.product.ui/src/org/uqbar/project/wollok/product/ui/startup/RemoveWizardsStartup.xtend
  org.uqbar.project.wollok.ui/plugin.properties
  org.uqbar.project.wollok.ui/plugin_es.properties
  org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/Messages.java
  org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/messages.properties
  org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/messages_es.properties
  org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/wizard/abstractWizards/AbstractNewWollokFileWizardPage.java
  org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/wizard/objects/NewWollokObjectsWizard.java
  org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/wizard/objects/NewWollokObjectsWizard.xtend
  org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/wizard/objects/NewWollokObjectsWizardPage.xtend
Labels: in progress

#1448 Fixing local maven build & new splash Gramsci
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/MessageSend.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/TypeInfo.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/TypeVariable.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/TypeVariableOwner.xtend
  org.uqbar.project.wollok.ui/icons/splash.fw.xcf
  org.uqbar.project.wollok.ui/old.splash.fw.png
  org.uqbar.project.wollok.ui/splash.bmp
  org.uqbar.project.wollok.ui/splash.fw.png
  org.uqbar.project.wollok.ui/splash.old.bmp
  org.uqbar.project.wollok.ui/splash.png
  org.uqbar.project.wollok.ui/splash/02_WLK_Imagotipo Neg.2.png
  org.uqbar.project.wollok.ui/splash/Gramsci.png
  org.uqbar.project.wollok.ui/splash/favicon.ico
  org.uqbar.project.wollok.ui/splash/splash..gramsci.xcf
  org.uqbar.project.wollok.ui/splash/splash_freire.xcf
  org.uqbar.project.wollok.ui/splash/uqbar.png
Labels: in progress

#1454 Fix #1439 revert deleted tests
  WollokFormatterProfile.xml
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/AbstractWollokTypeSystemTestCase.xtend
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/Issue1441_NoTypeMatchesUsage.wlk.xt
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/ObjetoMensajeZapatero2.wlk.xt
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/TypeSystemXpectTestCase.xtend
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/console.wpgm.xt
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/methods.wpgm.xt
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/util/XtendExtensionsTest.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/BasicType.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/StructuralType.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/WollokType.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/ConstraintGenerator.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/WollokModelPrintForDebug.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/strategies/GuessMinTypeFromMaxType.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/strategies/MaxTypesFromMessages.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/strategies/PropagateMaximalTypes.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/strategies/PropagateMinimalTypes.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/strategies/UnifyVariables.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/types/OffenderSelector.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/GenericTypeInfo.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/GenericTypeInstance.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/MaximalConcreteTypes.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/MessageSend.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/TypeInfo.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/TypeVariable.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/TypeVariableOwner.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/VoidTypeInfo.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WollokModelExtensions.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/utils/XtendExtensions.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/validation/AbstractConfigurableDslValidator.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/validation/WollokDslValidator.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/visitors/VariableUsesVisitor.xtend
Labels: in progress

#1453 Fix #1421 Bad unused variable validation
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/UnusedVariable.wlk.xt
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/xpect/UnusedVariable.wtest.xt
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/visitors/AbstractWollokVisitor.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/visitors/VariableUsesVisitor.xtend
Labels: component: validator, in progress

#1434 Adding MD viewer plugin
  org.uqbar.project.wollok.product/plugin.xml
  org.uqbar.project.wollok.targetplatform/org.uqbar.project.wollok.targetplatform.target
  org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/perspectives/WollokCodingPerspectiveFactory.xtend
  org.uqbar.project.wollok.updatesite/wollok-product.product
Labels: in progress

#1455 Fix #1401 - recursive relationships lead to stack overflow in toString
  org.uqbar.project.wollok.lib/src/wollok/lang.wlk
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/ListTestCase.xtend
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/RecursiveToStringTestCase.xtend
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/SetTestCase.xtend
Labels: in progress

#1457 Fix #1399 - missing import renders stack overflow
  org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/WollokLauncherInterpreterEvaluator.xtend
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/interpreter/imports/ImportsTest.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/errorHandling/HumanReadableUtils.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/WollokInterpreterEvaluator.xtend
Labels: component: interpreter, in progress

#1451 Fix #1405 - inherited properties are searched in a recursive and isol…
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WMethodContainerExtensions.xtend
Labels: component: validator, in progress

#1458 Fixes 1442 / Actually was already working, only add test
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/Issue1442_TypeCollectionAfterClosure.wlk.xt
Labels: in progress

#1460 Fix #1459 stack overflow ts wollok game
  org.uqbar.project.wollok.typeSystem.ui/src/org/uqbar/project/wollok/typeSystem/ui/builder/WollokTypeSystemBuilderParticipant.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/GenericType.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/ConstraintBasedTypeSystem.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/strategies/GuessMinTypeFromMaxType.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/strategies/MaxTypesFromMessages.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/typeRegistry/AnnotatedTypeRegistry.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/GenericTypeInfo.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/TypeVariable.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/TypeVariablesRegistry.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/utils/XtendExtensions.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/visitors/AbstractWollokVisitor.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/visitors/EffectFinderVisitor.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/visitors/ParameterUsesVisitor.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/visitors/ReturnFinderVisitor.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/visitors/VariableAssignmentsVisitor.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/visitors/VariableUsesVisitor.xtend
Labels: in progress

#1476 Fix #1340 ts not working for all ast nodes
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/AbstractWollokTypeSystemTestCase.xtend
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/ConsoleInferenceTestCase.xtend
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/InheritanceTypeInferenceTestCase.xtend
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/NamedObjectInferenceTestCase.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/CollectionTypeDeclarations.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/DateTypeDeclarations.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/ExceptionTypeDeclarations.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/NumberTypeDeclarations.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/StringTypeDeclarations.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/TypeDeclarations.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/WollokCoreTypeDeclarations.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/WollokGameTypeDeclarations.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/WollokLibTypeDeclarations.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/ConstraintBasedTypeSystem.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/ConstraintGenerator.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/WollokModelPrintForDebug.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/strategies/GuessMinTypeFromMaxType.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/VoidTypeInfo.xtend
  org.uqbar.project.wollok/src/org/uqbar/project/wollok/model/WollokModelExtensions.xtend
Labels: in progress

#1482 Fix travis build
  org.uqbar.project.wollok.releng/pom.xml
Labels: in progress

#1481 Console enhancements
  org.uqbar.project.wollok.launch/Generate WollokDoc.launch
  org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/Messages.java
  org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/messages.properties
  org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/messages_es.properties
  org.uqbar.project.wollok.launch/src/org/uqbar/project/wollok/launch/repl/WollokRepl.xtend
  org.uqbar.project.wollok.product.ui/src/org/uqbar/project/wollok/product/ui/startup/WollokPerspectiveListener.xtend
  org.uqbar.project.wollok.ui.launch/plugin.xml
  org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/console/WollokReplConsole.xtend
  org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/console/WollokReplConsolePage.xtend
  org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/launch/shortcut/WollokLaunchDelegate.xtend
  org.uqbar.project.wollok.ui.launch/src/org/uqbar/project/wollok/ui/launch/shortcut/WollokLaunchShortcut.xtend
  org.uqbar.project.wollok.ui/plugin.xml
  org.uqbar.project.wollok.ui/src/org/uqbar/project/wollok/ui/perspectives/WollokCodingPerspectiveFactory.xtend
Labels: component: repl, in progress

#1480 Fix #1479 self type return
  org.uqbar.project.wollok.tests/src/org/uqbar/project/wollok/tests/typesystem/xpect/list.wlk.xt
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/GenericType.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/CollectionTypeDeclarations.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/TypeAnnotation.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/annotations/TypeDeclarations.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/typeRegistry/AnnotatedTypeRegistry.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/typeRegistry/MethodTypeSchema.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/ClassParameterTypeVariable.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/CompoundSelfTypeVariableSchema.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/CompoundTypeVariableSchema.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/ITypeVariable.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/TypeVariableOwner.xtend
  org.uqbar.project.wollok.typeSystem/src/org/uqbar/project/wollok/typesystem/constraints/variables/TypeVariableSchema.xtend
Labels: in progress
